addappid(3469190)
addappid(3595930, 0, "d7bd563f47b269e38ea17014fd2cd6456378fbbfde50a5f172d04c750511ff7f")
setManifestid(3595930, "7940041631255530236", 0)
addappid(3469191, 2122454512, "50d374b0c0e272aff9b980f200e8813606e7b157616cfccad7c5318a30691369")
setManifestid(3469191, "9196905165020400977", 2440472721)
addappid(3469192, 28033840, "a5baa832c82725cc193f210b1ca1bd611ae8d45280cb521400ddf3753640fac1")
setManifestid(3469192, "214060425832483402", 101373999)

-- DLC's found without depots!
addappid(3470700) -- Touhou Spell Carnival - Gensokyo Safe Adventure Pack

-- Generated By [Manifest Dumper v3.2.2.9] ~ Game: Touhou Spell Carnival
-- Discord: toxichome ~ https://discord.gg/2bv9T3NfVP