addappid(3481320)
addappid(3481321, 193365280, "3f8cf034015d65424c4a36c2923b3570b9f833b4966d4cba5409fdd796dbc13f")
setManifestid(3481321, "4646982793544117980", 276934605)


-- Generated By [Manifest Dumper v3.2.2.9] ~ Game: Deckline
-- Discord: toxichome ~ https://discord.gg/2bv9T3NfVP