addappid(3534240)
addappid(3534241, 385106448, "78e1e5688e3f90979552754a36f01f3e4a4b7a863737e677e9accc0275758fd8")
setManifestid(3534241, "8913290595054170982", 976576990)


-- Generated By [Manifest Dumper v3.2.2.9] ~ Game: Uncanny Tales Cold Road
-- Discord: toxichome ~ https://discord.gg/2bv9T3NfVP